# Generated by Django 3.2.9 on 2022-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_donations_donatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donateDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
